### ISSUE TITLE
graph does not exist in N

### ISSUE THREAD

**Issue by live118** [99-66/zabbix-op-bot#4]
안녕하세요

그래프 목록 호출까지는 잘되는데, graph does not exist in 라는 메세지 호출이 되는데 확인해봐야 하는 항목이 있을까요?

**Comment by jintaekimmm** [comment]
> 안녕하세요
> 
> 그래프 목록 호출까지는 잘되는데, graph does not exist in 라는 메세지 호출이 되는데 확인해봐야 하는 항목이 있을까요?

@live118 안녕하세요. 답변이 늦었습니다!

1. 그래프1
2.그래프2
3.그래프3
과 같이 되어 있을 때, 선택하시면 에러가 나신다는게 맞나요?

현재 그래프를 선택할 때는 목록에서 보여주는 항목중에서 그래프 이름을 넘겨줘야 조회가 될 겁니다
ex) CPU jumps, CPU load, CPU utilization

순서 번호만 선택하게 코드를 바꿔서 답변드리려 했는데 테스트할 환경이 오늘 ~ 내일은 안될 것 같아 먼저 답변 드립니다
해당 부분은 가능하면 금주내에 반영해보도록 하겠습니다

감사합니다!

**Comment by live118** [comment]
아 번호가 아니라 이름이었군요 답변 감사합니다.

**Comment by live118** [comment]
FileNotFoundError: [Errno 2] No such file or directory: '/root/zabbix-op-bot/tmp_file/tmp_make_graph.png'

실제 파일 경로에 파일이 생성이 되지 않아 에러가 발생하네요.

폴더 권한 문제일까요 ?

**Comment by live118** [comment]
> FileNotFoundError: [Errno 2] No such file or directory: '/root/zabbix-op-bot/tmp_file/tmp_make_graph.png'
> 
> 실제 파일 경로에 파일이 생성이 되지 않아 에러가 발생하네요.
> 
> 폴더 권한 문제일까요 ?

해당 폴더에 tmp_file 폴더가 없어서 발생했네요 폴더 생성 후에 정상적으로 됩니다~

**Comment by live118** [comment]
그래프 item list 에서  퍼센트를 주로 그래프로 확인하는데 %때문에 그래프 list에 표출이 되지 않는걸까요?

아;; 찾았네요 감사합니다~
