### ISSUE TITLE
zbx_host_graph_resource period 

### ISSUE THREAD

**Issue by live118** [99-66/zabbix-op-bot#6]
zbx_host_graph_resource 함수에서

zabbix_graph_stime 24로 변경 해도 그래프 표출 기간은 3시간으로 나오네요!

graph_url에서 period 10800s 로 고정되어있는 것 같은데, 변경해도 안되서요.

변경 할 수있는 값이 따로 있을까요?

감사합니다~

**Comment by jintaekimmm** [comment]
> zbx_host_graph_resource 함수에서
> 
> zabbix_graph_stime 24로 변경 해도 그래프 표출 기간은 3시간으로 나오네요!
> 
> graph_url에서 period 10800s 로 고정되어있는 것 같은데, 변경해도 안되서요.
> 
> 변경 할 수있는 값이 따로 있을까요?
> 
> 감사합니다~

안녕하세요! 너무 늦게 답변드리네요

해당 문제는 'zabbix_graph_stime' 설정 값 외에 코드내에 'period' 쿼리스트링이 고정으로 되어 있어서 정상적으로 동작하지 않았습니다
현재는 'zabbix_graph_stime' 값에 따라서 정상적으로 그래프 시작 시간이 동작하도록 수정하였습니다

추가로 이전에 문의주셨던 내용 중에 그래프 선택 시에 이름이 아닌 번호만 선택하여도 동작하도록 반영되었습니다
Ex) 0. incomming interface graph eth0
1. incomming interface graph eth1
2. incomming interface graph eth2
3. incomming interface graph eth3
4. incomming interface graph lo

기존에는 'incomming interface graph eth3' 을 입력해야 동작하던 봇을
'3' 만을 입력해도 해당 번호의 그래프를 보여줍니다

감사합니다!

**Comment by live118** [comment]
오호 너무 감사합니다!~
